import type {
  ProductDetail,
  ProductSearchMeta,
  ProductSearchTermMeta,
} from "@/components/products/types";

function buildSearchMeta(input: {
  aliases: string[];
  search_terms: ProductSearchTermMeta[];
  source_type: string;
  source_ref: string | null;
  search_boost: number;
  storage_bucket: string | null;
  storage_path: string | null;
  alt_text: string | null;
  exact_match: boolean;
  direct_match: boolean;
  match_quality: ProductSearchMeta["match_quality"];
  score: number;
}): ProductSearchMeta {
  return {
    aliases: input.aliases,
    alias_entries: [],
    search_terms: input.search_terms,
    source_type: input.source_type,
    source_ref: input.source_ref,
    search_boost: input.search_boost,
    storage_bucket: input.storage_bucket,
    storage_path: input.storage_path,
    alt_text: input.alt_text,
    exact_match: input.exact_match,
    direct_match: input.direct_match,
    match_quality: input.match_quality,
    score: input.score,
  };
}

export const initialProductDetailsMock: ProductDetail[] = [
  {
    id: "bag_caminata_20x25_full",
    sku: "MWL-BAG-CAM-20X25-FULL",
    family: "caminata",
    name: "Caminata 20x25 cm Full Sublimada",
    category: "bolsos",
    variant_label: "premium",
    size_label: "20x25 cm",
    width_cm: 20,
    height_cm: 25,
    depth_cm: null,
    material: "tela poliester",
    base_color: null,
    print_type: "full sublimacion",
    personalization_area: "completa",
    price_crc: 2500,
    price_from_crc: null,
    min_qty: 5,
    allows_name: true,
    includes_design_adjustment_count: 1,
    extra_adjustment_has_cost: true,
    requires_design_approval: true,
    is_full_color: true,
    is_premium: true,
    is_discountable: true,
    discount_visibility: "only_if_customer_requests",
    pricing_mode: "fixed",
    summary: "Bolso tipo caminata completamente sublimado.",
    details: "Parte trasera puede ser de color. Opcion totalmente colorida.",
    notes:
      "Tiene descuento del 5% solo en pedidos mayores a 15 unidades. El agente no debe ofrecerlo si el cliente no lo pide.",
    source_type: "owner_direct",
    source_ref: "Actualizacion manual bolsos marzo 2026",
    is_active: true,
    is_agent_visible: true,
    sort_order: 120,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 5,
    images: [
      {
        id: 4,
        product_id: "bag_caminata_20x25_full",
        storage_bucket: "mwl-products",
        storage_path: "products/bag_caminata_20x25_full/main.jpeg",
        alt_text: "Bolso tipo caminata 20x25 cm full sublimado",
        is_primary: true,
        sort_order: 0,
        created_at: "2026-03-09T16:15:27.000Z",
      },
    ],
    search_meta: buildSearchMeta({
      aliases: [
        "bolso caminata",
        "bolso premium caminata",
        "bolso tipo caminata",
        "caminata colorida",
        "caminata full sublimada",
        "caminata premium",
      ],
      search_terms: [
        {
          id: 53,
          product_id: "bag_caminata_20x25_full",
          family: null,
          category: null,
          term: "caminata premium",
          term_type: "alias",
          priority: 90,
          is_active: true,
          notes: null,
          created_at: "2026-03-10T02:50:00.000Z",
        },
      ],
      source_type: "owner_direct",
      source_ref: "Actualizacion manual bolsos marzo 2026",
      search_boost: 5,
      storage_bucket: "mwl-products",
      storage_path: "products/bag_caminata_20x25_full/main.jpeg",
      alt_text: "Bolso tipo caminata 20x25 cm full sublimado",
      exact_match: false,
      direct_match: true,
      match_quality: "strong",
      score: 7.77,
    }),
    discount_rules: [
      {
        id: 1,
        product_id: "bag_caminata_20x25_full",
        min_qty: 16,
        discount_percent: 5,
        discount_amount_crc: null,
        rule_type: "never_offer_proactively",
        notes:
          "Aplicar solo si el cliente pregunta por descuento o cotiza cantidad alta. Nunca ofrecer de forma espontanea.",
        is_active: true,
      },
    ],
    range_prices: [],
    ui_created_locally: false,
  },
  {
    id: "bag_confitero_20x25_std",
    sku: "MWL-BAG-CONF-20X25-STD",
    family: "confitero",
    name: "Confitero 20x25 cm",
    category: "bolsos",
    variant_label: "estandar",
    size_label: "20x25 cm",
    width_cm: 20,
    height_cm: 25,
    depth_cm: null,
    material: "tela poliester",
    base_color: "blanco",
    print_type: "sublimacion frontal",
    personalization_area: "frontal",
    price_crc: 1000,
    price_from_crc: null,
    min_qty: 5,
    allows_name: true,
    includes_design_adjustment_count: 1,
    extra_adjustment_has_cost: true,
    requires_design_approval: true,
    is_full_color: false,
    is_premium: false,
    is_discountable: false,
    discount_visibility: "only_if_customer_requests",
    pricing_mode: "fixed",
    summary: "Bolso confitero en tela blanca.",
    details: "Personalizacion tematica frontal.",
    notes: "Se puede incluir nombre del invitado sin costo adicional.",
    source_type: "owner_direct",
    source_ref: "Actualizacion manual bolsos marzo 2026",
    is_active: true,
    is_agent_visible: true,
    sort_order: 80,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 3,
    images: [
      {
        id: 5,
        product_id: "bag_confitero_20x25_std",
        storage_bucket: "mwl-products",
        storage_path: "products/bag_confitero_20x25_std/main.jpeg",
        alt_text: "Bolso tipo caminata 20x25 cm standard",
        is_primary: true,
        sort_order: 0,
        created_at: "2026-03-09T16:17:40.000Z",
      },
    ],
    search_meta: buildSearchMeta({
      aliases: ["confitero", "saquito confitero", "bolso confitero", "candy bag tela"],
      search_terms: [
        {
          id: 37,
          product_id: "bag_confitero_20x25_std",
          family: null,
          category: null,
          term: "bolso confitero",
          term_type: "alias",
          priority: 80,
          is_active: true,
          notes: null,
          created_at: "2026-03-10T02:50:00.000Z",
        },
      ],
      source_type: "owner_direct",
      source_ref: "Actualizacion manual bolsos marzo 2026",
      search_boost: 3,
      storage_bucket: "mwl-products",
      storage_path: "products/bag_confitero_20x25_std/main.jpeg",
      alt_text: "Bolso tipo caminata 20x25 cm standard",
      exact_match: true,
      direct_match: true,
      match_quality: "exact",
      score: 11.65,
    }),
    discount_rules: [],
    range_prices: [],
    ui_created_locally: false,
  },
  {
    id: "kit_creativo_std",
    sku: "MWL-KIT-CREATIVO-STD",
    family: "kit_creativo",
    name: "Kit creativo personalizado",
    category: "kits",
    variant_label: "estandar",
    size_label: null,
    width_cm: null,
    height_cm: null,
    depth_cm: null,
    material: null,
    base_color: null,
    print_type: null,
    personalization_area: null,
    price_crc: null,
    price_from_crc: 4500,
    min_qty: 10,
    allows_name: true,
    includes_design_adjustment_count: 0,
    extra_adjustment_has_cost: false,
    requires_design_approval: true,
    is_full_color: false,
    is_premium: false,
    is_discountable: false,
    discount_visibility: "never",
    pricing_mode: "range",
    summary: "Kit personalizado para celebraciones.",
    details: "Incluye libro de colorear, vaso personalizado, bolso confitero y crayolas.",
    notes: null,
    source_type: "catalog_pdf",
    source_ref: "Fiestas2026.pdf",
    is_active: true,
    is_agent_visible: true,
    sort_order: 30,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 0,
    images: [],
    search_meta: buildSearchMeta({
      aliases: ["combo creativo", "kit creativo", "kit personalizado"],
      search_terms: [
        {
          id: 15,
          product_id: "kit_creativo_std",
          family: null,
          category: null,
          term: "kit creativo",
          term_type: "alias",
          priority: 60,
          is_active: true,
          notes: null,
          created_at: "2026-03-10T02:50:00.000Z",
        },
      ],
      source_type: "catalog_pdf",
      source_ref: "Fiestas2026.pdf",
      search_boost: 0,
      storage_bucket: null,
      storage_path: null,
      alt_text: null,
      exact_match: false,
      direct_match: true,
      match_quality: "strong",
      score: 2.47,
    }),
    discount_rules: [],
    range_prices: [
      {
        id: 101,
        product_id: "kit_creativo_std",
        range_min_qty: 10,
        range_max_qty: 19,
        unit_price_crc: 4300,
        sort_order: 0,
        is_active: true,
        created_at: "2026-03-10T10:00:00.000Z",
      },
      {
        id: 102,
        product_id: "kit_creativo_std",
        range_min_qty: 20,
        range_max_qty: null,
        unit_price_crc: 4100,
        sort_order: 1,
        is_active: true,
        created_at: "2026-03-10T10:00:00.000Z",
      },
    ],
    ui_created_locally: false,
  },
  {
    id: "cups_vinyl_std",
    sku: "MWL-CUP-VINYL-STD",
    family: "vasos_personalizados",
    name: "Vasos personalizados",
    category: "vasos",
    variant_label: "estandar",
    size_label: null,
    width_cm: null,
    height_cm: null,
    depth_cm: null,
    material: "plastico",
    base_color: null,
    print_type: "vinil",
    personalization_area: "frontal",
    price_crc: 2200,
    price_from_crc: null,
    min_qty: 1,
    allows_name: false,
    includes_design_adjustment_count: 0,
    extra_adjustment_has_cost: false,
    requires_design_approval: true,
    is_full_color: false,
    is_premium: false,
    is_discountable: false,
    discount_visibility: "never",
    pricing_mode: "fixed",
    summary: "Vasos personalizados estampados en vinil.",
    details: null,
    notes: null,
    source_type: "catalog_pdf",
    source_ref: "Fiestas2026.pdf",
    is_active: true,
    is_agent_visible: true,
    sort_order: 150,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 0,
    images: [
      {
        id: 6,
        product_id: "cups_vinyl_std",
        storage_bucket: "mwl-products",
        storage_path: "products/cups_vinyl_std/main.jpeg",
        alt_text: "Vaso personalizado",
        is_primary: true,
        sort_order: 0,
        created_at: "2026-03-09T16:18:56.000Z",
      },
    ],
    search_meta: buildSearchMeta({
      aliases: ["vasos", "vasos personalizados", "vasos en vinil"],
      search_terms: [
        {
          id: 44,
          product_id: "cups_vinyl_std",
          family: null,
          category: null,
          term: "vasos personalizados",
          term_type: "alias",
          priority: 75,
          is_active: true,
          notes: null,
          created_at: "2026-03-10T02:50:00.000Z",
        },
      ],
      source_type: "catalog_pdf",
      source_ref: "Fiestas2026.pdf",
      search_boost: 0,
      storage_bucket: "mwl-products",
      storage_path: "products/cups_vinyl_std/main.jpeg",
      alt_text: "Vaso personalizado",
      exact_match: true,
      direct_match: true,
      match_quality: "exact",
      score: 10.2,
    }),
    discount_rules: [],
    range_prices: [],
    ui_created_locally: false,
  },
  {
    id: "book_coloring_std",
    sku: "MWL-BOOK-COLORING-STD",
    family: "libro_colorear",
    name: "Libro para colorear personalizado",
    category: "coleccion_creativa",
    variant_label: "estandar",
    size_label: "1/2 carta",
    width_cm: null,
    height_cm: null,
    depth_cm: null,
    material: "papel impreso + portada cartulina",
    base_color: null,
    print_type: "impresion alta calidad",
    personalization_area: "portada e interiores",
    price_crc: 1600,
    price_from_crc: null,
    min_qty: 1,
    allows_name: true,
    includes_design_adjustment_count: 0,
    extra_adjustment_has_cost: false,
    requires_design_approval: true,
    is_full_color: false,
    is_premium: false,
    is_discountable: false,
    discount_visibility: "never",
    pricing_mode: "fixed",
    summary: "Libro para colorear totalmente personalizado.",
    details:
      "Formato 1/2 carta, impresion de excelente calidad, portada resistente y 20 paginas internas.",
    notes: null,
    source_type: "catalog_pdf",
    source_ref: "Fiestas2026.pdf",
    is_active: true,
    is_agent_visible: true,
    sort_order: 10,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 0,
    images: [],
    search_meta: buildSearchMeta({
      aliases: ["libro para colorear", "libro de colorear", "cuaderno para colorear"],
      search_terms: [
        {
          id: 5,
          product_id: "book_coloring_std",
          family: null,
          category: null,
          term: "libro para colorear",
          term_type: "alias",
          priority: 65,
          is_active: true,
          notes: null,
          created_at: "2026-03-10T02:50:00.000Z",
        },
      ],
      source_type: "catalog_pdf",
      source_ref: "Fiestas2026.pdf",
      search_boost: 0,
      storage_bucket: null,
      storage_path: null,
      alt_text: null,
      exact_match: false,
      direct_match: false,
      match_quality: "strong",
      score: 1.4,
    }),
    discount_rules: [],
    range_prices: [],
    ui_created_locally: false,
  },
  {
    id: "banner_flags_std",
    sku: "MWL-BANNER-FLAGS-STD",
    family: "banderines",
    name: "Banderines personalizados",
    category: "decoracion",
    variant_label: "estandar",
    size_label: null,
    width_cm: null,
    height_cm: null,
    depth_cm: null,
    material: null,
    base_color: null,
    print_type: null,
    personalization_area: null,
    price_crc: null,
    price_from_crc: null,
    min_qty: 1,
    allows_name: false,
    includes_design_adjustment_count: 0,
    extra_adjustment_has_cost: false,
    requires_design_approval: true,
    is_full_color: false,
    is_premium: false,
    is_discountable: false,
    discount_visibility: "never",
    pricing_mode: "range",
    summary: null,
    details: null,
    notes: "Producto desactivado para revision comercial interna.",
    source_type: "catalog_pdf",
    source_ref: "Fiestas2026.pdf",
    is_active: false,
    is_agent_visible: false,
    sort_order: 50,
    updated_at: "2026-03-07T21:53:30.778Z",
    search_boost: 0,
    images: [],
    search_meta: buildSearchMeta({
      aliases: [],
      search_terms: [],
      source_type: "catalog_pdf",
      source_ref: "Fiestas2026.pdf",
      search_boost: 0,
      storage_bucket: null,
      storage_path: null,
      alt_text: null,
      exact_match: false,
      direct_match: false,
      match_quality: "weak",
      score: 0.2,
    }),
    discount_rules: [],
    range_prices: [],
    ui_created_locally: false,
  },
];
