CREATE TABLE IF NOT EXISTS "public"."mwl_product_range_prices" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_id" "text" NOT NULL,
    "range_min_qty" integer NOT NULL,
    "range_max_qty" integer,
    "unit_price_crc" integer NOT NULL,
    "sort_order" integer DEFAULT 0 NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "mwl_product_range_prices_range_min_qty_check" CHECK (("range_min_qty" > 0)),
    CONSTRAINT "mwl_product_range_prices_unit_price_crc_check" CHECK (("unit_price_crc" > 0)),
    CONSTRAINT "mwl_product_range_prices_range_max_qty_check" CHECK (("range_max_qty" IS NULL) OR ("range_max_qty" >= "range_min_qty"))
);

ALTER TABLE "public"."mwl_product_range_prices"
ADD CONSTRAINT "mwl_product_range_prices_product_id_fkey"
FOREIGN KEY ("product_id") REFERENCES "public"."mwl_products"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "idx_mwl_product_range_prices_product_id"
ON "public"."mwl_product_range_prices" ("product_id");

CREATE INDEX IF NOT EXISTS "idx_mwl_product_range_prices_product_active"
ON "public"."mwl_product_range_prices" ("product_id", "is_active");

CREATE INDEX IF NOT EXISTS "idx_mwl_product_range_prices_product_qty"
ON "public"."mwl_product_range_prices" ("product_id", "range_min_qty", "range_max_qty");

CREATE OR REPLACE FUNCTION "public"."validate_product_range_prices"() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.range_min_qty <= 0 THEN
        RAISE EXCEPTION 'range_min_qty must be greater than 0';
    END IF;

    IF NEW.unit_price_crc <= 0 THEN
        RAISE EXCEPTION 'unit_price_crc must be greater than 0';
    END IF;

    IF NEW.range_max_qty IS NOT NULL AND NEW.range_max_qty < NEW.range_min_qty THEN
        RAISE EXCEPTION 'range_max_qty must be greater than or equal to range_min_qty';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM public.mwl_products p
        WHERE p.id = NEW.product_id
    ) THEN
        RAISE EXCEPTION 'Producto no encontrado';
    END IF;

    IF NEW.is_active THEN
        IF EXISTS (
            SELECT 1
            FROM public.mwl_product_range_prices r
            WHERE r.product_id = NEW.product_id
              AND r.is_active = true
              AND r.id <> COALESCE(NEW.id, 0)
              AND NOT (
                  COALESCE(r.range_max_qty, 2147483647) < NEW.range_min_qty
                  OR COALESCE(NEW.range_max_qty, 2147483647) < r.range_min_qty
              )
        ) THEN
            RAISE EXCEPTION 'Rangos estructurales solapados';
        END IF;

        IF NEW.range_max_qty IS NULL AND EXISTS (
            SELECT 1
            FROM public.mwl_product_range_prices r
            WHERE r.product_id = NEW.product_id
              AND r.is_active = true
              AND r.id <> COALESCE(NEW.id, 0)
              AND r.range_max_qty IS NULL
        ) THEN
            RAISE EXCEPTION 'Solo se permite un rango abierto activo por producto';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "trg_validate_product_range_prices" ON "public"."mwl_product_range_prices";

CREATE TRIGGER "trg_validate_product_range_prices"
BEFORE INSERT OR UPDATE ON "public"."mwl_product_range_prices"
FOR EACH ROW
EXECUTE FUNCTION "public"."validate_product_range_prices"();

ALTER TABLE "public"."mwl_products"
DROP CONSTRAINT IF EXISTS "mwl_products_pricing_mode_check";

ALTER TABLE "public"."mwl_products"
ADD CONSTRAINT "mwl_products_pricing_mode_check"
CHECK (("pricing_mode" = ANY (ARRAY['fixed'::text, 'range'::text, 'variable'::text])))
NOT VALID;

UPDATE "public"."mwl_products"
SET "pricing_mode" = 'range'
WHERE "pricing_mode" = 'from';

ALTER TABLE "public"."mwl_products"
VALIDATE CONSTRAINT "mwl_products_pricing_mode_check";

CREATE OR REPLACE FUNCTION "public"."mwl_resolve_product_pricing"(
    "p_product_id" "text",
    "p_qty" integer,
    "p_now" timestamp with time zone DEFAULT "now"()
) RETURNS "jsonb"
LANGUAGE plpgsql
AS $$
DECLARE
    v_product RECORD;
    v_promo RECORD;
    v_block RECORD;
    v_range RECORD;
    v_first_range RECORD;

    v_qty_rounded integer;
    v_blocks integer;
    v_total integer;
    v_base_mode text;
BEGIN
    SELECT * INTO v_product
    FROM public.mwl_products
    WHERE id = p_product_id;

    IF v_product IS NULL THEN
        RAISE EXCEPTION 'Producto no encontrado';
    END IF;

    IF v_product.min_qty IS NOT NULL AND p_qty < v_product.min_qty THEN
        RETURN jsonb_build_object(
            'mode', 'min_qty_not_met',
            'qty', p_qty,
            'min_qty', v_product.min_qty,
            'pricing_mode', v_product.pricing_mode
        );
    END IF;

    SELECT *
    INTO v_promo
    FROM public.mwl_product_promotions
    WHERE product_id = p_product_id
      AND is_enabled = true
      AND agent_visible = true
      AND p_now BETWEEN starts_at AND ends_at
    LIMIT 1;

    IF v_promo IS NULL THEN
        v_base_mode := 'base';
    ELSIF p_qty < v_promo.min_promo_qty THEN
        v_base_mode := 'base_below_promo';
    END IF;

    IF v_base_mode IS NOT NULL THEN
        IF v_product.pricing_mode = 'variable' THEN
            RETURN jsonb_build_object(
                'mode', 'manual_required',
                'qty', p_qty,
                'pricing_mode', v_product.pricing_mode,
                'reason', v_base_mode
            );
        END IF;

        IF v_product.pricing_mode = 'fixed' THEN
            RETURN jsonb_build_object(
                'mode', v_base_mode,
                'qty', p_qty,
                'pricing_mode', v_product.pricing_mode,
                'unit_price', COALESCE(v_product.price_crc, v_product.price_from_crc),
                'total', p_qty * COALESCE(v_product.price_crc, v_product.price_from_crc)
            );
        END IF;

        IF v_product.pricing_mode = 'range' THEN
            SELECT *
            INTO v_first_range
            FROM public.mwl_product_range_prices r
            WHERE r.product_id = p_product_id
              AND r.is_active = true
            ORDER BY r.range_min_qty ASC, r.sort_order ASC, r.id ASC
            LIMIT 1;

            IF v_first_range IS NULL OR p_qty < v_first_range.range_min_qty THEN
                RETURN jsonb_build_object(
                    'mode', v_base_mode,
                    'qty', p_qty,
                    'pricing_mode', 'range',
                    'unit_price', COALESCE(v_product.price_from_crc, v_product.price_crc),
                    'total', p_qty * COALESCE(v_product.price_from_crc, v_product.price_crc)
                );
            END IF;

            SELECT *
            INTO v_range
            FROM public.mwl_product_range_prices r
            WHERE r.product_id = p_product_id
              AND r.is_active = true
              AND p_qty >= r.range_min_qty
              AND (r.range_max_qty IS NULL OR p_qty <= r.range_max_qty)
            ORDER BY r.range_min_qty ASC, r.sort_order ASC, r.id ASC
            LIMIT 1;

            IF v_range IS NOT NULL THEN
                RETURN jsonb_build_object(
                    'mode', v_base_mode,
                    'qty', p_qty,
                    'pricing_mode', 'range',
                    'unit_price', v_range.unit_price_crc,
                    'total', p_qty * v_range.unit_price_crc,
                    'range_min_qty', v_range.range_min_qty,
                    'range_max_qty', v_range.range_max_qty
                );
            END IF;

            RETURN jsonb_build_object(
                'mode', 'configuration_invalid',
                'qty', p_qty,
                'pricing_mode', 'range',
                'reason', 'range_gap_uncovered_qty'
            );
        END IF;

        RETURN jsonb_build_object(
            'mode', v_base_mode,
            'qty', p_qty,
            'pricing_mode', v_product.pricing_mode,
            'unit_price', COALESCE(v_product.price_crc, v_product.price_from_crc),
            'total', p_qty * COALESCE(v_product.price_crc, v_product.price_from_crc)
        );
    END IF;

    IF v_promo.promo_type = 'blocks' THEN
        SELECT * INTO v_block
        FROM public.mwl_product_promotion_block_prices
        WHERE promotion_id = v_promo.id
          AND exact_qty = p_qty;

        IF v_block IS NOT NULL THEN
            RETURN jsonb_build_object(
                'mode', 'block_exact',
                'qty', p_qty,
                'total', v_block.total_price_crc
            );
        END IF;

        IF p_qty <= v_promo.top_block_qty THEN
            v_qty_rounded :=
                ceil(p_qty::numeric / v_promo.block_size) * v_promo.block_size;

            SELECT * INTO v_block
            FROM public.mwl_product_promotion_block_prices
            WHERE promotion_id = v_promo.id
              AND exact_qty = v_qty_rounded;

            RETURN jsonb_build_object(
                'mode', 'block_round_up',
                'requested_qty', p_qty,
                'suggested_qty', v_qty_rounded,
                'total', v_block.total_price_crc
            );
        END IF;

        v_qty_rounded :=
            ceil(p_qty::numeric / v_promo.block_size) * v_promo.block_size;

        v_blocks := v_qty_rounded / v_promo.block_size;

        v_total := v_blocks * v_promo.post_top_block_price_crc;

        RETURN jsonb_build_object(
            'mode', 'block_post_top',
            'requested_qty', p_qty,
            'quoted_qty', v_qty_rounded,
            'total', v_total
        );
    END IF;

    IF v_promo.promo_type = 'ranges' THEN
        SELECT *
        INTO v_range
        FROM public.mwl_product_promotion_range_prices
        WHERE promotion_id = v_promo.id
          AND p_qty >= range_min_qty
          AND (range_max_qty IS NULL OR p_qty <= range_max_qty)
        LIMIT 1;

        IF v_range IS NULL THEN
            RAISE EXCEPTION 'No hay rango válido';
        END IF;

        RETURN jsonb_build_object(
            'mode', 'range',
            'qty', p_qty,
            'unit_price', v_range.unit_price_crc,
            'total', p_qty * v_range.unit_price_crc
        );
    END IF;

    RETURN NULL;
END;
$$;
